name: PR

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK 5
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.x'

      - name: Clean
        run: dotnet clean Skanderborg.Graduering.sln --configuration Release && dotnet nuget locals all --clear

      - name: Install dependencies
        run: dotnet restore Skanderborg.Graduering.sln

      - name: Build
        run: dotnet build Skanderborg.Graduering.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Skanderborg.Graduering.sln --configuration Release --no-restore